version: '3.8'

services:
  minio:
    image: bitnami/minio:2024-debian-12
    platform: linux/arm64 # for mac devices
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ~/Documents/minio_data:/data  # Bind mount for Documents folder
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=test

